AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  back_autorizaciones

Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
      Environment:
        Variables:
          DB_HOST: host.docker.internal
          DB_PORT: "3307"
          DB_USER: root
          DB_PASS: admin
          DB_NAME: test_db
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts

  ConsultarAutorizacionesFuncition:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: consultarAutorizaciones.consultarAutorizacionesHandler
      Runtime: nodejs20.x
      Timeout: 20
      Events:
        ApiConsultarAutorizaciones:
          Type: Api
          Properties:
            Path: /consulta-autorizacion
            Method: post
      Environment:
        Variables:
          DB_HOST: host.docker.internal
          DB_PORT: "3307"
          DB_USER: root
          DB_PASS: admin
          DB_NAME: test_db
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - consultarAutorizaciones.ts

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"

  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn

  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn

  ConsultarAutorizacionesEndpoint:
    Description: "Consultar Autorizaciones API Gateway"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/consulta-autorizacion"
